---
- name: Install dependencies for Prometheus on Ubuntu
  apt:
    name: curl
    state: present

- name: Download Prometheus tarball
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus tarball
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create symbolic link for Prometheus
  file:
    src: /opt/prometheus-2.30.3.linux-amd64
    dest: /opt/prometheus
    state: link

- name: Copy Prometheus service file
  copy:
    content: |
      [Unit]
      Description=Prometheus
      Documentation=https://prometheus.io/docs/introduction/overview/
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      ExecStart=/opt/prometheus/prometheus --config.file /opt/prometheus/prometheus.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
